import type { ColorSeed } from "@/lib/types";

// Generated by scripts/generate-color-seeds.mjs. Do not edit this file by hand.
export const colorSeeds: ColorSeed[] = [
  {
    "id": "bao-lan",
    "sourceId": "zerosoul-3-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "宝蓝",
    "namePinyin": "bao lan",
    "hex": "#4b5cc4",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "bi-lan",
    "sourceId": "zerosoul-3-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "碧蓝",
    "namePinyin": "bi lan",
    "hex": "#3eede7",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "玉石",
      "清透"
    ],
    "sourceNote": ""
  },
  {
    "id": "dai-lan",
    "sourceId": "zerosoul-3-11",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黛蓝",
    "namePinyin": "dai lan",
    "hex": "#425066",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "深远",
      "远山"
    ],
    "sourceNote": ""
  },
  {
    "id": "dai-lv",
    "sourceId": "zerosoul-3-10",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黛绿",
    "namePinyin": "dai lv",
    "hex": "#426666",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "dai-zi",
    "sourceId": "zerosoul-3-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黛紫",
    "namePinyin": "dai zi",
    "hex": "#574266",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "远山",
      "含蓄"
    ],
    "sourceNote": ""
  },
  {
    "id": "dian-lan",
    "sourceId": "zerosoul-3-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "靛蓝",
    "namePinyin": "dian lan",
    "hex": "#065279",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "深远",
      "染色"
    ],
    "sourceNote": ""
  },
  {
    "id": "dian-qing",
    "sourceId": "zerosoul-3-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "靛青",
    "namePinyin": "dian qing",
    "hex": "#177cb0",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "ding-xiang-se",
    "sourceId": "zerosoul-3-22",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "丁香色",
    "namePinyin": "ding xiang se",
    "hex": "#cca4e3",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "紫系",
      "典雅"
    ],
    "sourceNote": ""
  },
  {
    "id": "jiang-zi",
    "sourceId": "zerosoul-3-15",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "酱紫",
    "namePinyin": "jiang zi",
    "hex": "#815476",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "lan",
    "sourceId": "zerosoul-3-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "蓝",
    "namePinyin": "lan",
    "hex": "#44cef6",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "深远"
    ],
    "sourceNote": ""
  },
  {
    "id": "lan-hui-se",
    "sourceId": "zerosoul-3-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "蓝灰色",
    "namePinyin": "lan hui se",
    "hex": "#a1afc9",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "深远",
      "灰系"
    ],
    "sourceNote": ""
  },
  {
    "id": "ou-se",
    "sourceId": "zerosoul-3-23",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "藕色",
    "namePinyin": "ou se",
    "hex": "#edd1d8",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "qun-qing",
    "sourceId": "ccc-curated-qun-qing",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "群青",
    "namePinyin": "qun qing",
    "hex": "#1772b4",
    "family": "blue",
    "moodTags": [
      "矿物",
      "深远",
      "稳定"
    ],
    "sourceNote": ""
  },
  {
    "id": "tian-qing",
    "sourceId": "ccc-curated-tian-qing",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "天青",
    "namePinyin": "tian qing",
    "hex": "#2e59a7",
    "family": "blue",
    "moodTags": [
      "天空",
      "瓷色",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "wei-lan",
    "sourceId": "zerosoul-3-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "蔚蓝",
    "namePinyin": "wei lan",
    "hex": "#70f3ff",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "深远",
      "天空"
    ],
    "sourceNote": ""
  },
  {
    "id": "xue-qing",
    "sourceId": "zerosoul-3-21",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "雪青",
    "namePinyin": "xue qing",
    "hex": "#b0a4e3",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "zang-lan",
    "sourceId": "zerosoul-3-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "藏蓝",
    "namePinyin": "zang lan",
    "hex": "#3b2e7e",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "zang-qing",
    "sourceId": "zerosoul-3-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "藏青",
    "namePinyin": "zang qing",
    "hex": "#2e4e7e",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "zi-jiang",
    "sourceId": "zerosoul-3-14",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "紫酱",
    "namePinyin": "zi jiang",
    "hex": "#815463",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "紫系",
      "典雅"
    ],
    "sourceNote": ""
  },
  {
    "id": "绀青绀紫",
    "sourceId": "zerosoul-3-17",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "绀青绀紫",
    "namePinyin": "绀青绀紫",
    "hex": "#003371",
    "family": "blue",
    "moodTags": [
      "蓝系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "mi-tuo-seng",
    "sourceId": "ccc-curated-mi-tuo-seng",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "密陀僧",
    "namePinyin": "mi tuo seng",
    "hex": "#b35c44",
    "family": "brown",
    "moodTags": [
      "土色",
      "沉着",
      "温润"
    ],
    "sourceNote": ""
  },
  {
    "id": "zi-tang",
    "sourceId": "ccc-curated-zi-tang",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "紫檀",
    "namePinyin": "zi tan",
    "hex": "#4c221b",
    "family": "brown",
    "moodTags": [
      "木器",
      "厚重",
      "收藏"
    ],
    "sourceNote": ""
  },
  {
    "id": "ya-dan-qing",
    "sourceId": "ccc-curated-ya-dan-qing",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "鸭蛋青",
    "namePinyin": "ya dan qing",
    "hex": "#e0eee8",
    "family": "cyan",
    "moodTags": [
      "瓷器",
      "浅淡",
      "洁净"
    ],
    "sourceNote": ""
  },
  {
    "id": "yue-bai",
    "sourceId": "ccc-curated-yue-bai",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "月白",
    "namePinyin": "yue bai",
    "hex": "#d6ecf0",
    "family": "cyan",
    "moodTags": [
      "月色",
      "清冷",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "an",
    "sourceId": "zerosoul-7-14",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黯",
    "namePinyin": "an",
    "hex": "#41555d",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重"
    ],
    "sourceNote": ""
  },
  {
    "id": "cang-bai",
    "sourceId": "zerosoul-4-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍白",
    "namePinyin": "cang bai",
    "hex": "#d1d9e0",
    "family": "gray",
    "moodTags": [
      "苍系",
      "自然",
      "古朴"
    ],
    "sourceNote": ""
  },
  {
    "id": "cang-hei",
    "sourceId": "zerosoul-4-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍黑",
    "namePinyin": "cang hei",
    "hex": "#395260",
    "family": "gray",
    "moodTags": [
      "苍系",
      "自然",
      "古朴"
    ],
    "sourceNote": ""
  },
  {
    "id": "cang-huang",
    "sourceId": "zerosoul-4-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍黄",
    "namePinyin": "cang huang",
    "hex": "#a29b7c",
    "family": "gray",
    "moodTags": [
      "苍系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "cang-qing",
    "sourceId": "zerosoul-4-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍青",
    "namePinyin": "cang qing",
    "hex": "#7397ab",
    "family": "gray",
    "moodTags": [
      "苍系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "cang-se",
    "sourceId": "zerosoul-4-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍色",
    "namePinyin": "cang se",
    "hex": "#75878a",
    "family": "gray",
    "moodTags": [
      "苍系",
      "自然",
      "古朴"
    ],
    "sourceNote": ""
  },
  {
    "id": "dan-qing",
    "sourceId": "zerosoul-5-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "淡青",
    "namePinyin": "dan qing",
    "hex": "#d3e0f3",
    "family": "gray",
    "moodTags": [
      "水系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "gao",
    "sourceId": "zerosoul-6-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "缟",
    "namePinyin": "gao",
    "hex": "#f2ecde",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "hei-se",
    "sourceId": "zerosoul-7-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黑色",
    "namePinyin": "hei se",
    "hex": "#000000",
    "family": "gray",
    "moodTags": [
      "黑系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "hu-lan",
    "sourceId": "zerosoul-5-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "湖蓝",
    "namePinyin": "hu lan",
    "hex": "#30dff3",
    "family": "gray",
    "moodTags": [
      "水系",
      "蓝系",
      "深远"
    ],
    "sourceNote": ""
  },
  {
    "id": "hu-lv",
    "sourceId": "zerosoul-5-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "湖绿",
    "namePinyin": "hu lv",
    "hex": "#25f8cb",
    "family": "gray",
    "moodTags": [
      "水系",
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "hua-bai",
    "sourceId": "zerosoul-6-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "花白",
    "namePinyin": "hua bai",
    "hex": "#c2ccd0",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "hui-se",
    "sourceId": "zerosoul-6-11",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "灰色",
    "namePinyin": "hui se",
    "hex": "#808080",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "jing-bai",
    "sourceId": "zerosoul-6-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "精白",
    "namePinyin": "jing bai",
    "hex": "#ffffff",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "柔和",
      "妆色"
    ],
    "sourceNote": ""
  },
  {
    "id": "li",
    "sourceId": "zerosoul-7-11",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黎",
    "namePinyin": "li",
    "hex": "#75664d",
    "family": "gray",
    "moodTags": [
      "黑系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "mei-hei",
    "sourceId": "zerosoul-7-9",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "煤黑",
    "namePinyin": "mei hei",
    "hex": "#312520",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重"
    ],
    "sourceNote": ""
  },
  {
    "id": "mo-hui",
    "sourceId": "zerosoul-7-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "墨灰",
    "namePinyin": "mo hui",
    "hex": "#758a99",
    "family": "gray",
    "moodTags": [
      "黑系",
      "灰系",
      "克制"
    ],
    "sourceNote": ""
  },
  {
    "id": "mo-se",
    "sourceId": "zerosoul-7-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "墨色",
    "namePinyin": "mo se",
    "hex": "#50616d",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重",
      "书写"
    ],
    "sourceNote": ""
  },
  {
    "id": "qi-hei",
    "sourceId": "zerosoul-7-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "漆黑",
    "namePinyin": "qi hei",
    "hex": "#161823",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重"
    ],
    "sourceNote": ""
  },
  {
    "id": "qian-bai",
    "sourceId": "zerosoul-6-13",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "铅白",
    "namePinyin": "qian bai",
    "hex": "#f0f0f4",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "柔和",
      "妆色"
    ],
    "sourceNote": ""
  },
  {
    "id": "shuang-se",
    "sourceId": "zerosoul-6-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "霜色",
    "namePinyin": "shuang se",
    "hex": "#e9f1f6",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "shui-hong",
    "sourceId": "zerosoul-5-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "水红",
    "namePinyin": "shui hong",
    "hex": "#f3d3e7",
    "family": "gray",
    "moodTags": [
      "水系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "shui-lan",
    "sourceId": "zerosoul-5-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "水蓝",
    "namePinyin": "shui lan",
    "hex": "#d2f0f4",
    "family": "gray",
    "moodTags": [
      "水系",
      "蓝系",
      "深远"
    ],
    "sourceNote": ""
  },
  {
    "id": "shui-lv",
    "sourceId": "zerosoul-5-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "水绿",
    "namePinyin": "shui lv",
    "hex": "#d4f2e7",
    "family": "gray",
    "moodTags": [
      "水系",
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "shui-se",
    "sourceId": "zerosoul-5-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "水色",
    "namePinyin": "shui se",
    "hex": "#88ada6",
    "family": "gray",
    "moodTags": [
      "水系",
      "水色",
      "清透"
    ],
    "sourceNote": ""
  },
  {
    "id": "su",
    "sourceId": "zerosoul-6-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "素",
    "namePinyin": "su",
    "hex": "#e0f0e9",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "tu-bai",
    "sourceId": "zerosoul-6-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "荼白",
    "namePinyin": "tu bai",
    "hex": "#f3f9f1",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "wu-hei",
    "sourceId": "zerosoul-7-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "乌黑",
    "namePinyin": "wu hei",
    "hex": "#392f41",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重",
      "深色"
    ],
    "sourceNote": ""
  },
  {
    "id": "wu-se",
    "sourceId": "zerosoul-7-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "乌色",
    "namePinyin": "wu se",
    "hex": "#725e82",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重",
      "深色"
    ],
    "sourceNote": ""
  },
  {
    "id": "xiang-ya-bai",
    "sourceId": "zerosoul-6-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "象牙白",
    "namePinyin": "xiang ya bai",
    "hex": "#fffbf0",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "xuan-qing",
    "sourceId": "ccc-curated-xuan-qing",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "玄青",
    "namePinyin": "xuan qing",
    "hex": "#3d3b4f",
    "family": "gray",
    "moodTags": [
      "夜色",
      "庄重",
      "深沉"
    ],
    "sourceNote": ""
  },
  {
    "id": "xuan-se",
    "sourceId": "zerosoul-7-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "玄色",
    "namePinyin": "xuan se",
    "hex": "#622a1d",
    "family": "gray",
    "moodTags": [
      "黑系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "xue-bai",
    "sourceId": "zerosoul-6-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "雪白",
    "namePinyin": "xue bai",
    "hex": "#f2fdff",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "ya-se",
    "sourceId": "zerosoul-6-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "牙色",
    "namePinyin": "ya se",
    "hex": "#eedeb0",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "ying-bai",
    "sourceId": "zerosoul-6-10",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "莹白",
    "namePinyin": "ying bai",
    "hex": "#e3f9fd",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "you",
    "sourceId": "zerosoul-7-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黝",
    "namePinyin": "you",
    "hex": "#6b6882",
    "family": "gray",
    "moodTags": [
      "黑系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "you-hei",
    "sourceId": "zerosoul-7-13",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黝黑",
    "namePinyin": "you hei",
    "hex": "#665757",
    "family": "gray",
    "moodTags": [
      "黑系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "yu-du-bai",
    "sourceId": "zerosoul-6-9",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "鱼肚白",
    "namePinyin": "yu du bai",
    "hex": "#fcefe8",
    "family": "gray",
    "moodTags": [
      "灰白系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "zi-se",
    "sourceId": "zerosoul-7-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "缁色",
    "namePinyin": "zi se",
    "hex": "#493131",
    "family": "gray",
    "moodTags": [
      "黑系",
      "庄重"
    ],
    "sourceNote": ""
  },
  {
    "id": "苍翠",
    "sourceId": "zerosoul-4-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "苍翠",
    "namePinyin": "苍翠",
    "hex": "#519a73",
    "family": "gray",
    "moodTags": [
      "苍系",
      "自然",
      "古朴"
    ],
    "sourceNote": ""
  },
  {
    "id": "ai-lv",
    "sourceId": "zerosoul-2-28",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "艾绿",
    "namePinyin": "ai lv",
    "hex": "#a4e2c6",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "清新"
    ],
    "sourceNote": ""
  },
  {
    "id": "bi-lv",
    "sourceId": "zerosoul-2-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "碧绿",
    "namePinyin": "bi lv",
    "hex": "#2add9c",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "玉石"
    ],
    "sourceNote": ""
  },
  {
    "id": "bi-se",
    "sourceId": "zerosoul-2-11",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "碧色",
    "namePinyin": "bi se",
    "hex": "#1bd1a5",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "玉石"
    ],
    "sourceNote": ""
  },
  {
    "id": "cao-lv",
    "sourceId": "zerosoul-2-15",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "草绿",
    "namePinyin": "cao lv",
    "hex": "#40de5a",
    "family": "green",
    "moodTags": [
      "绿系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "cong-huang",
    "sourceId": "zerosoul-2-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "葱黄",
    "namePinyin": "cong huang",
    "hex": "#a3d900",
    "family": "green",
    "moodTags": [
      "绿系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "cong-lv",
    "sourceId": "zerosoul-2-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "葱绿",
    "namePinyin": "cong lv",
    "hex": "#9ed900",
    "family": "green",
    "moodTags": [
      "绿系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "cong-qing",
    "sourceId": "zerosoul-2-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "葱青",
    "namePinyin": "cong qing",
    "hex": "#0eb83a",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "鲜活"
    ],
    "sourceNote": ""
  },
  {
    "id": "dou-lv",
    "sourceId": "zerosoul-2-23",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "豆绿",
    "namePinyin": "dou lv",
    "hex": "#9ed048",
    "family": "green",
    "moodTags": [
      "绿系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "dou-qing",
    "sourceId": "zerosoul-2-24",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "豆青",
    "namePinyin": "dou qing",
    "hex": "#96ce54",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "fei-cui-se",
    "sourceId": "zerosoul-2-14",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "翡翠色",
    "namePinyin": "fei cui se",
    "hex": "#3de1ad",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "玉石"
    ],
    "sourceNote": ""
  },
  {
    "id": "liu-huang",
    "sourceId": "zerosoul-2-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "柳黄",
    "namePinyin": "liu huang",
    "hex": "#c9dd22",
    "family": "green",
    "moodTags": [
      "绿系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "liu-lv",
    "sourceId": "zerosoul-2-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "柳绿",
    "namePinyin": "liu lv",
    "hex": "#afdd22",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "春日"
    ],
    "sourceNote": ""
  },
  {
    "id": "lv-se",
    "sourceId": "zerosoul-2-22",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "绿色",
    "namePinyin": "lv se",
    "hex": "#00e500",
    "family": "green",
    "moodTags": [
      "绿系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "lv-shen",
    "sourceId": "zerosoul-2-10",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "绿沈",
    "namePinyin": "lv shen",
    "hex": "#0c8918",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "nen-lv",
    "sourceId": "zerosoul-2-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "嫩绿",
    "namePinyin": "nen lv",
    "hex": "#bddd22",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "piao",
    "sourceId": "zerosoul-2-27",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "缥",
    "namePinyin": "piao",
    "hex": "#7fecad",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "白系"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-bai",
    "sourceId": "zerosoul-2-18",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "青白",
    "namePinyin": "qing bai",
    "hex": "#c0ebd7",
    "family": "green",
    "moodTags": [
      "绿系",
      "青系",
      "清朗"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-bi",
    "sourceId": "zerosoul-2-13",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "青碧",
    "namePinyin": "qing bi",
    "hex": "#48c0a3",
    "family": "green",
    "moodTags": [
      "绿系",
      "玉石",
      "清透"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-cong",
    "sourceId": "zerosoul-2-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "青葱",
    "namePinyin": "qing cong",
    "hex": "#0aa344",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "鲜活"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-cui",
    "sourceId": "zerosoul-2-17",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "青翠",
    "namePinyin": "qing cui",
    "hex": "#00e079",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-se",
    "sourceId": "zerosoul-2-16",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "青色",
    "namePinyin": "qing se",
    "hex": "#00e09e",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "shi-qing",
    "sourceId": "zerosoul-2-25",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "石青",
    "namePinyin": "shi qing",
    "hex": "#7bcfa6",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "song-bai-lv",
    "sourceId": "zerosoul-2-29",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "松柏绿",
    "namePinyin": "song bai lv",
    "hex": "#21a675",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "沉静"
    ],
    "sourceNote": ""
  },
  {
    "id": "song-hua",
    "sourceId": "ccc-curated-song-hua",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "松花",
    "namePinyin": "song hua",
    "hex": "#bce672",
    "family": "green",
    "moodTags": [
      "植物",
      "清新",
      "早春"
    ],
    "sourceNote": ""
  },
  {
    "id": "song-hua-lv",
    "sourceId": "zerosoul-2-30",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "松花绿",
    "namePinyin": "song hua lv",
    "hex": "#057748",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "沉静"
    ],
    "sourceNote": ""
  },
  {
    "id": "xie-ke-qing",
    "sourceId": "zerosoul-2-20",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "蟹壳青",
    "namePinyin": "xie ke qing",
    "hex": "#bbcdc5",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "ya-qing",
    "sourceId": "zerosoul-2-21",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "鸦青",
    "namePinyin": "ya qing",
    "hex": "#424c50",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "you-lv",
    "sourceId": "zerosoul-2-9",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "油绿",
    "namePinyin": "you lv",
    "hex": "#00bc12",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "yu-se",
    "sourceId": "zerosoul-2-26",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "玉色",
    "namePinyin": "yu se",
    "hex": "#2edfa3",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "青系"
    ],
    "sourceNote": ""
  },
  {
    "id": "zhu-qing",
    "sourceId": "ccc-curated-zhu-qing",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "竹青",
    "namePinyin": "zhu qing",
    "hex": "#789262",
    "family": "green",
    "moodTags": [
      "竹影",
      "文雅",
      "安静"
    ],
    "sourceNote": ""
  },
  {
    "id": "葱倩",
    "sourceId": "zerosoul-2-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "葱倩",
    "namePinyin": "葱倩",
    "hex": "#0eb840",
    "family": "green",
    "moodTags": [
      "绿系",
      "植物",
      "鲜活"
    ],
    "sourceNote": ""
  },
  {
    "id": "hu-po",
    "sourceId": "ccc-curated-hu-po",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "琥珀",
    "namePinyin": "hu po",
    "hex": "#ca6924",
    "family": "orange",
    "moodTags": [
      "器物",
      "通透",
      "暖意"
    ],
    "sourceNote": ""
  },
  {
    "id": "xiong-huang",
    "sourceId": "ccc-curated-xiong-huang",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "雄黄",
    "namePinyin": "xiong huang",
    "hex": "#ff9900",
    "family": "orange",
    "moodTags": [
      "矿物",
      "明亮",
      "端午"
    ],
    "sourceNote": ""
  },
  {
    "id": "ou-he",
    "sourceId": "ccc-curated-ou-he",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "藕荷",
    "namePinyin": "ou he",
    "hex": "#e4c6d0",
    "family": "pink",
    "moodTags": [
      "荷花",
      "柔婉",
      "浅淡"
    ],
    "sourceNote": ""
  },
  {
    "id": "dai",
    "sourceId": "ccc-curated-dai",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "黛",
    "namePinyin": "dai",
    "hex": "#4a4266",
    "family": "purple",
    "moodTags": [
      "远山",
      "眉色",
      "含蓄"
    ],
    "sourceNote": ""
  },
  {
    "id": "qing-lian",
    "sourceId": "ccc-curated-qing-lian",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "青莲",
    "namePinyin": "qing lian",
    "hex": "#801dae",
    "family": "purple",
    "moodTags": [
      "花色",
      "典雅",
      "神秘"
    ],
    "sourceNote": ""
  },
  {
    "id": "chi",
    "sourceId": "zerosoul-0-21",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "赤",
    "namePinyin": "chi",
    "hex": "#c3272b",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "da-hong",
    "sourceId": "zerosoul-0-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "大红",
    "namePinyin": "da hong",
    "hex": "#ff2121",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "dan",
    "sourceId": "zerosoul-0-13",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "丹",
    "namePinyin": "dan",
    "hex": "#ff4e20",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "矿物"
    ],
    "sourceNote": ""
  },
  {
    "id": "fei-hong",
    "sourceId": "zerosoul-0-10",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "绯红",
    "namePinyin": "fei hong",
    "hex": "#c83c23",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "fei-se",
    "sourceId": "zerosoul-0-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "妃色",
    "namePinyin": "fei se",
    "hex": "#ed5736",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "柔和"
    ],
    "sourceNote": ""
  },
  {
    "id": "fen-hong",
    "sourceId": "zerosoul-0-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "粉红",
    "namePinyin": "fen hong",
    "hex": "#ffb3a7",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "柔和"
    ],
    "sourceNote": ""
  },
  {
    "id": "hai-tang-hong",
    "sourceId": "zerosoul-0-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "海棠红",
    "namePinyin": "hai tang hong",
    "hex": "#db5a6b",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "花色"
    ],
    "sourceNote": ""
  },
  {
    "id": "he-chi",
    "sourceId": "zerosoul-0-17",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "赫赤",
    "namePinyin": "he chi",
    "hex": "#c91f37",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "huo-hong",
    "sourceId": "zerosoul-0-16",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "火红",
    "namePinyin": "huo hong",
    "hex": "#ff2d51",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "luo-xia-hong",
    "sourceId": "ccc-curated-luo-xia-hong",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "落霞红",
    "namePinyin": "luo xia hong",
    "hex": "#cf4813",
    "family": "red",
    "moodTags": [
      "暮色",
      "热烈",
      "古典"
    ],
    "sourceNote": ""
  },
  {
    "id": "pin-hong",
    "sourceId": "zerosoul-0-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "品红",
    "namePinyin": "pin hong",
    "hex": "#f00056",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "qian-se",
    "sourceId": "zerosoul-0-15",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "茜色",
    "namePinyin": "qian se",
    "hex": "#cb3a56",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "shi-liu-hong",
    "sourceId": "ccc-curated-shi-liu-hong",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "石榴红",
    "namePinyin": "shi liu hong",
    "hex": "#f20c00",
    "family": "red",
    "moodTags": [
      "果实",
      "明快",
      "节庆"
    ],
    "sourceNote": ""
  },
  {
    "id": "tan",
    "sourceId": "zerosoul-0-24",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "檀",
    "namePinyin": "tan",
    "hex": "#b36d61",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "木器"
    ],
    "sourceNote": ""
  },
  {
    "id": "tao-hong",
    "sourceId": "zerosoul-0-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "桃红",
    "namePinyin": "tao hong",
    "hex": "#f47983",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "柔和"
    ],
    "sourceNote": ""
  },
  {
    "id": "tong",
    "sourceId": "zerosoul-0-14",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "彤",
    "namePinyin": "tong",
    "hex": "#f35336",
    "family": "red",
    "moodTags": [
      "红系"
    ],
    "sourceNote": ""
  },
  {
    "id": "tuo-hong",
    "sourceId": "zerosoul-0-26",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "酡红",
    "namePinyin": "tuo hong",
    "hex": "#dc3023",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "tuo-yan",
    "sourceId": "zerosoul-0-27",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "酡颜",
    "namePinyin": "tuo yan",
    "hex": "#f9906f",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "wan",
    "sourceId": "zerosoul-0-22",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "绾",
    "namePinyin": "wan",
    "hex": "#a98175",
    "family": "red",
    "moodTags": [
      "红系"
    ],
    "sourceNote": ""
  },
  {
    "id": "yan",
    "sourceId": "zerosoul-0-20",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "炎",
    "namePinyin": "yan",
    "hex": "#ff3300",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "yan-hong",
    "sourceId": "zerosoul-0-25",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "殷红",
    "namePinyin": "yan hong",
    "hex": "#be002f",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "黑系"
    ],
    "sourceNote": ""
  },
  {
    "id": "yan-zhi",
    "sourceId": "ccc-curated-yan-zhi",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "胭脂",
    "namePinyin": "yan zhi",
    "hex": "#9d2933",
    "family": "red",
    "moodTags": [
      "妆色",
      "浓郁",
      "礼制"
    ],
    "sourceNote": ""
  },
  {
    "id": "yang-hong",
    "sourceId": "zerosoul-0-19",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "洋红",
    "namePinyin": "yang hong",
    "hex": "#ff0097",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "黄系"
    ],
    "sourceNote": ""
  },
  {
    "id": "yin-hong",
    "sourceId": "zerosoul-0-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "银红",
    "namePinyin": "yin hong",
    "hex": "#f05654",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "柔和"
    ],
    "sourceNote": ""
  },
  {
    "id": "ying-tao-se",
    "sourceId": "zerosoul-0-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "樱桃色",
    "namePinyin": "ying tao se",
    "hex": "#c93756",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "花色"
    ],
    "sourceNote": ""
  },
  {
    "id": "zao-hong",
    "sourceId": "zerosoul-0-23",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "枣红",
    "namePinyin": "zao hong",
    "hex": "#c32136",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "zhu-hong",
    "sourceId": "zerosoul-0-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "朱红",
    "namePinyin": "zhu hong",
    "hex": "#ff4c00",
    "family": "red",
    "moodTags": [
      "红系",
      "明艳",
      "矿物"
    ],
    "sourceNote": ""
  },
  {
    "id": "zhu-sha",
    "sourceId": "ccc-curated-zhu-sha",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "朱砂",
    "namePinyin": "zhu sha",
    "hex": "#ff461f",
    "family": "red",
    "moodTags": [
      "矿物",
      "醒目",
      "仪式"
    ],
    "sourceNote": ""
  },
  {
    "id": "cheng-huang",
    "sourceId": "zerosoul-1-6",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "橙黄",
    "namePinyin": "cheng huang",
    "hex": "#ffa400",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "cheng-se",
    "sourceId": "zerosoul-1-10",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "橙色",
    "namePinyin": "cheng se",
    "hex": "#fa8c35",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "chi-jin",
    "sourceId": "zerosoul-8-0",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "赤金",
    "namePinyin": "chi jin",
    "hex": "#f2be45",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "金属",
      "贵重"
    ],
    "sourceNote": ""
  },
  {
    "id": "e-huang",
    "sourceId": "ccc-curated-e-huang",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "鹅黄",
    "namePinyin": "e huang",
    "hex": "#fff143",
    "family": "yellow",
    "moodTags": [
      "春日",
      "轻盈",
      "鲜活"
    ],
    "sourceNote": ""
  },
  {
    "id": "he-se",
    "sourceId": "zerosoul-1-23",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "褐色",
    "namePinyin": "he se",
    "hex": "#6e511e",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "黑系"
    ],
    "sourceNote": ""
  },
  {
    "id": "huang-lu",
    "sourceId": "zerosoul-1-25",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "黄栌",
    "namePinyin": "huang lu",
    "hex": "#e29c45",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "hun-huang",
    "sourceId": "zerosoul-1-13",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "昏黄",
    "namePinyin": "hun huang",
    "hex": "#c89b40",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "jiang-huang",
    "sourceId": "zerosoul-1-8",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "姜黄",
    "namePinyin": "jiang huang",
    "hex": "#ffc773",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "草木"
    ],
    "sourceNote": ""
  },
  {
    "id": "jin-se",
    "sourceId": "zerosoul-8-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "金色",
    "namePinyin": "jin se",
    "hex": "#eacd76",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "ju-hong",
    "sourceId": "zerosoul-1-7",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "橘红",
    "namePinyin": "ju hong",
    "hex": "#ff7500",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "ju-huang",
    "sourceId": "zerosoul-1-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "橘黄",
    "namePinyin": "ju huang",
    "hex": "#ff8936",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "果实"
    ],
    "sourceNote": ""
  },
  {
    "id": "ku-huang",
    "sourceId": "zerosoul-1-24",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "枯黄",
    "namePinyin": "ku huang",
    "hex": "#d3b17d",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "lao-yin",
    "sourceId": "zerosoul-8-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "老银",
    "namePinyin": "lao yin",
    "hex": "#bacac6",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "金属",
      "贵重"
    ],
    "sourceNote": ""
  },
  {
    "id": "li-se",
    "sourceId": "zerosoul-1-14",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "栗色",
    "namePinyin": "li se",
    "hex": "#60281e",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "果实",
      "厚重"
    ],
    "sourceNote": ""
  },
  {
    "id": "qiu-se",
    "sourceId": "zerosoul-1-26",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "秋色",
    "namePinyin": "qiu se",
    "hex": "#896c39",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "土色",
      "沉着"
    ],
    "sourceNote": ""
  },
  {
    "id": "qiu-xiang-se",
    "sourceId": "zerosoul-1-27",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "秋香色",
    "namePinyin": "qiu xiang se",
    "hex": "#d9b611",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "绿系"
    ],
    "sourceNote": ""
  },
  {
    "id": "tong-lv",
    "sourceId": "zerosoul-8-5",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "铜绿",
    "namePinyin": "tong lv",
    "hex": "#549688",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "绿系",
      "植物"
    ],
    "sourceNote": ""
  },
  {
    "id": "tuo-se",
    "sourceId": "zerosoul-1-12",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "驼色",
    "namePinyin": "tuo se",
    "hex": "#a88462",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "wu-jin",
    "sourceId": "zerosoul-8-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "乌金",
    "namePinyin": "wu jin",
    "hex": "#a78e44",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "深色",
      "沉稳"
    ],
    "sourceNote": ""
  },
  {
    "id": "xiang-se",
    "sourceId": "zerosoul-1-9",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "缃色",
    "namePinyin": "xiang se",
    "hex": "#f0c239",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖"
    ],
    "sourceNote": ""
  },
  {
    "id": "xing-hong",
    "sourceId": "zerosoul-1-4",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "杏红",
    "namePinyin": "xing hong",
    "hex": "#ff8c31",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "xing-huang",
    "sourceId": "zerosoul-1-3",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "杏黄",
    "namePinyin": "xing huang",
    "hex": "#ffa631",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "果实"
    ],
    "sourceNote": ""
  },
  {
    "id": "ya-huang",
    "sourceId": "zerosoul-1-1",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "鸭黄",
    "namePinyin": "ya huang",
    "hex": "#faff72",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "浅淡"
    ],
    "sourceNote": ""
  },
  {
    "id": "yao-huang",
    "sourceId": "ccc-curated-yao-huang",
    "sourceName": "ccc curated colors",
    "sourceUrl": "https://github.com/xuCesar/chinese-classical-colors",
    "license": "Project curated data",
    "reliability": "curated",
    "nameZh": "姚黄",
    "namePinyin": "yao huang",
    "hex": "#d0deaa",
    "family": "yellow",
    "moodTags": [
      "牡丹",
      "柔和",
      "清雅"
    ],
    "sourceNote": ""
  },
  {
    "id": "yin-bai",
    "sourceId": "zerosoul-8-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "银白",
    "namePinyin": "yin bai",
    "hex": "#e9e7ef",
    "family": "yellow",
    "moodTags": [
      "金银系",
      "白系",
      "留白"
    ],
    "sourceNote": ""
  },
  {
    "id": "ying-cao-se",
    "sourceId": "zerosoul-1-2",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "樱草色",
    "namePinyin": "ying cao se",
    "hex": "#eaff56",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "果实",
      "鲜活"
    ],
    "sourceNote": ""
  },
  {
    "id": "zhe",
    "sourceId": "zerosoul-1-20",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "赭",
    "namePinyin": "zhe",
    "hex": "#9c5333",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "zong-hei",
    "sourceId": "zerosoul-1-17",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "棕黑",
    "namePinyin": "zong hei",
    "hex": "#7c4b00",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "土色",
      "沉着"
    ],
    "sourceNote": ""
  },
  {
    "id": "zong-hong",
    "sourceId": "zerosoul-1-18",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "棕红",
    "namePinyin": "zong hong",
    "hex": "#9b4400",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "zong-huang",
    "sourceId": "zerosoul-1-19",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "棕黄",
    "namePinyin": "zong huang",
    "hex": "#ae7000",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "温暖",
      "土色"
    ],
    "sourceNote": ""
  },
  {
    "id": "zong-lv",
    "sourceId": "zerosoul-1-16",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "棕绿",
    "namePinyin": "zong lv",
    "hex": "#827100",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "土色",
      "沉着"
    ],
    "sourceNote": ""
  },
  {
    "id": "zong-se",
    "sourceId": "zerosoul-1-15",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "棕色",
    "namePinyin": "zong se",
    "hex": "#b25d25",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  },
  {
    "id": "赭色",
    "sourceId": "zerosoul-1-21",
    "sourceName": "zerosoul/chinese-colors",
    "sourceUrl": "https://github.com/zerosoul/chinese-colors",
    "license": "MIT",
    "reliability": "open-source",
    "nameZh": "赭色",
    "namePinyin": "赭色",
    "hex": "#955539",
    "family": "yellow",
    "moodTags": [
      "黄系",
      "红系",
      "明艳"
    ],
    "sourceNote": ""
  }
];
